### ISSUE TITLE
Mapping personnes

### ISSUE THREAD

**Issue by jdp1ps** [jdp1ps/oscar#10]

**Comment by jdp1ps** [comment]
- [ ] Inversion nom prénom (sn = nom de famille, givenName = prénom)
- [ ] Mail : prendre le champs mail
- [ ] Identifiant : uid
- [ ] Localisation : buildingName
- [ ] affectation : prendre supannEntiteAffectation -> supannCodeEntite
- [ ] rôle dans l'affectation : supannCodeEntite
supannRoleEntite : liste des codes rôles (pour l'instant : directeur de labo)
- "Directeur de laboratoire"  -> ["{UAI:0751717J:HARPEGE.FCSTR}530"]

**Comment by Siso51** [comment]
Inversion nom / prenom effectué
PRise en compte du champ mail effectué
Identifiant uid effectué
Affectation effectué

Role dans affectation pas clair et supannroleEntite absent

Mise a jour de la branche connecteurLdapPersonne avec celle ci

**Comment by Siso51** [comment]
Role affecté FAIT - merge dans connecteurLdapPersonne effectué

**Comment by Siso51** [comment]
Role lié à une organisation FAIT - merge dans connecteurLdapPersonne effectué
