### ISSUE TITLE
Mails ou téléphones manquants

### ISSUE THREAD

**Issue by jdp1ps** [jdp1ps/oscar#5]
Apparaissent de façon un peu aléatoire

**Comment by Siso51** [comment]
Vu avec Benoit, les comptes ne renvoient aucun mail sur le LDAP de test car les comptes sont tous inactifs. Il a autorisé l'envoi des adresses mails pour les comptes inactifs du coup, c'est bon. Pour les telephones ils sont pas tout le temps renseignés.
