### ISSUE TITLE
Mappings organisations

### ISSUE THREAD

**Issue by jdp1ps** [jdp1ps/oscar#9]

**Comment by jdp1ps** [comment]
Il y a au minimum 2 valeurs, voire 3, dans le supannRefId -> prendre l'attribut en multivalué
- [ ] RNSR : dans supannRefId avec étiquette RNSR
- [ ] Labintel : dans supannRefId avec étiquette CNRS (historiquement)

**Comment by jdp1ps** [comment]
Pas d'email des organisations

**Comment by jdp1ps** [comment]
Pas de SIRET

**Comment by jdp1ps** [comment]
Typologie sur supannTypeEntite : 
- Laboratoire (UMR et UP)
- Composante (UFR et assimilés)

**Comment by jdp1ps** [comment]
Id LDAP = supannCodeEntite

**Comment by Siso51** [comment]
RNSR et Labintel effectué 
Pas de siret donc normal
Pas de mail donc normal

En attente de typologie pour supannTypeEntite

IdLdap effectué

Branche mergé avec connecteurLdapPersonnes

**Comment by Siso51** [comment]
Typologie des entreprise faite !
A savoir qu'aucune des organizations remontés n'ont une typologie correspondante donc pour ceux qui ont une typologie, elle remonte en typologie 'inconnue' et ceux qui en ont pas, c'est vide.
Mergé avec connecteurLDAPpersonnes
